// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: snapshotplugin.proto

package snapshotpluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeProviderPlugin_FetchSnapshot_FullMethodName  = "/snapshotplugin.v1.NodeProviderPlugin/FetchSnapshot"
	NodeProviderPlugin_UploadSnapshot_FullMethodName = "/snapshotplugin.v1.NodeProviderPlugin/UploadSnapshot"
)

// NodeProviderPluginClient is the client API for NodeProviderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeProviderPlugin is the plugin API a snapshot storage platform implements
// on every node. atelet calls it to move actor snapshots between the node and
// the platform's storage. How the platform stores them (object names,
// compression, block devices) is private to the plugin. The only requirement is
// that FetchSnapshot returns the bytes UploadSnapshot was given.
//
// Callers name every file they want moved. A snapshot's file list lives in
// its manifest, which the caller fetches first by name. The caller also owns
// commit ordering: it uploads the data files, and only after that call
// succeeds does it upload the manifest in a separate call, so a reader that
// finds the manifest can rely on every file it lists.
//
// Every RPC is idempotent: a retry overwrites whatever an earlier attempt
// stored or wrote.
type NodeProviderPluginClient interface {
	// FetchSnapshot downloads the named files of a snapshot into write_path.
	// It returns NOT_FOUND if any requested file is absent from the snapshot.
	// A plugin that authorizes per actor returns PERMISSION_DENIED if actor_jwt
	// does not grant read access to snapshot_uri.
	FetchSnapshot(ctx context.Context, in *FetchSnapshotRequest, opts ...grpc.CallOption) (*FetchSnapshotResponse, error)
	// UploadSnapshot uploads the named files from local_path into a snapshot.
	// It returns success only once every file is durably stored. A plugin that
	// authorizes per actor returns PERMISSION_DENIED if actor_jwt does not grant
	// write access to snapshot_uri.
	UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*UploadSnapshotResponse, error)
}

type nodeProviderPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeProviderPluginClient(cc grpc.ClientConnInterface) NodeProviderPluginClient {
	return &nodeProviderPluginClient{cc}
}

func (c *nodeProviderPluginClient) FetchSnapshot(ctx context.Context, in *FetchSnapshotRequest, opts ...grpc.CallOption) (*FetchSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeProviderPlugin_FetchSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeProviderPluginClient) UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*UploadSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeProviderPlugin_UploadSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeProviderPluginServer is the server API for NodeProviderPlugin service.
// All implementations must embed UnimplementedNodeProviderPluginServer
// for forward compatibility.
//
// NodeProviderPlugin is the plugin API a snapshot storage platform implements
// on every node. atelet calls it to move actor snapshots between the node and
// the platform's storage. How the platform stores them (object names,
// compression, block devices) is private to the plugin. The only requirement is
// that FetchSnapshot returns the bytes UploadSnapshot was given.
//
// Callers name every file they want moved. A snapshot's file list lives in
// its manifest, which the caller fetches first by name. The caller also owns
// commit ordering: it uploads the data files, and only after that call
// succeeds does it upload the manifest in a separate call, so a reader that
// finds the manifest can rely on every file it lists.
//
// Every RPC is idempotent: a retry overwrites whatever an earlier attempt
// stored or wrote.
type NodeProviderPluginServer interface {
	// FetchSnapshot downloads the named files of a snapshot into write_path.
	// It returns NOT_FOUND if any requested file is absent from the snapshot.
	// A plugin that authorizes per actor returns PERMISSION_DENIED if actor_jwt
	// does not grant read access to snapshot_uri.
	FetchSnapshot(context.Context, *FetchSnapshotRequest) (*FetchSnapshotResponse, error)
	// UploadSnapshot uploads the named files from local_path into a snapshot.
	// It returns success only once every file is durably stored. A plugin that
	// authorizes per actor returns PERMISSION_DENIED if actor_jwt does not grant
	// write access to snapshot_uri.
	UploadSnapshot(context.Context, *UploadSnapshotRequest) (*UploadSnapshotResponse, error)
	mustEmbedUnimplementedNodeProviderPluginServer()
}

// UnimplementedNodeProviderPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeProviderPluginServer struct{}

func (UnimplementedNodeProviderPluginServer) FetchSnapshot(context.Context, *FetchSnapshotRequest) (*FetchSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchSnapshot not implemented")
}
func (UnimplementedNodeProviderPluginServer) UploadSnapshot(context.Context, *UploadSnapshotRequest) (*UploadSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSnapshot not implemented")
}
func (UnimplementedNodeProviderPluginServer) mustEmbedUnimplementedNodeProviderPluginServer() {}
func (UnimplementedNodeProviderPluginServer) testEmbeddedByValue()                            {}

// UnsafeNodeProviderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeProviderPluginServer will
// result in compilation errors.
type UnsafeNodeProviderPluginServer interface {
	mustEmbedUnimplementedNodeProviderPluginServer()
}

func RegisterNodeProviderPluginServer(s grpc.ServiceRegistrar, srv NodeProviderPluginServer) {
	// If the following call panics, it indicates UnimplementedNodeProviderPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeProviderPlugin_ServiceDesc, srv)
}

func _NodeProviderPlugin_FetchSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeProviderPluginServer).FetchSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeProviderPlugin_FetchSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeProviderPluginServer).FetchSnapshot(ctx, req.(*FetchSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeProviderPlugin_UploadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeProviderPluginServer).UploadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeProviderPlugin_UploadSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeProviderPluginServer).UploadSnapshot(ctx, req.(*UploadSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeProviderPlugin_ServiceDesc is the grpc.ServiceDesc for NodeProviderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshotplugin.v1.NodeProviderPlugin",
	HandlerType: (*NodeProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchSnapshot",
			Handler:    _NodeProviderPlugin_FetchSnapshot_Handler,
		},
		{
			MethodName: "UploadSnapshot",
			Handler:    _NodeProviderPlugin_UploadSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snapshotplugin.proto",
}

const (
	ServerProviderPlugin_CleanupSnapshot_FullMethodName = "/snapshotplugin.v1.ServerProviderPlugin/CleanupSnapshot"
	ServerProviderPlugin_CopySnapshot_FullMethodName    = "/snapshotplugin.v1.ServerProviderPlugin/CopySnapshot"
)

// ServerProviderPluginClient is the client API for ServerProviderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServerProviderPlugin is the plugin API a snapshot storage platform
// implements for the control plane. ate-api-server calls it to manage whole
// snapshots.
type ServerProviderPluginClient interface {
	// CleanupSnapshot deletes every file of a snapshot, or of every snapshot
	// under an owner's prefix. Deleting an absent snapshot succeeds.
	CleanupSnapshot(ctx context.Context, in *CleanupSnapshotRequest, opts ...grpc.CallOption) (*CleanupSnapshotResponse, error)
	// CopySnapshot copies every file of src_uri to dst_uri, overwriting files
	// already at dst_uri. src_uri and dst_uri may be in different buckets. It
	// returns FAILED_PRECONDITION if src_uri holds no files.
	CopySnapshot(ctx context.Context, in *CopySnapshotRequest, opts ...grpc.CallOption) (*CopySnapshotResponse, error)
}

type serverProviderPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewServerProviderPluginClient(cc grpc.ClientConnInterface) ServerProviderPluginClient {
	return &serverProviderPluginClient{cc}
}

func (c *serverProviderPluginClient) CleanupSnapshot(ctx context.Context, in *CleanupSnapshotRequest, opts ...grpc.CallOption) (*CleanupSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupSnapshotResponse)
	err := c.cc.Invoke(ctx, ServerProviderPlugin_CleanupSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverProviderPluginClient) CopySnapshot(ctx context.Context, in *CopySnapshotRequest, opts ...grpc.CallOption) (*CopySnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopySnapshotResponse)
	err := c.cc.Invoke(ctx, ServerProviderPlugin_CopySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerProviderPluginServer is the server API for ServerProviderPlugin service.
// All implementations must embed UnimplementedServerProviderPluginServer
// for forward compatibility.
//
// ServerProviderPlugin is the plugin API a snapshot storage platform
// implements for the control plane. ate-api-server calls it to manage whole
// snapshots.
type ServerProviderPluginServer interface {
	// CleanupSnapshot deletes every file of a snapshot, or of every snapshot
	// under an owner's prefix. Deleting an absent snapshot succeeds.
	CleanupSnapshot(context.Context, *CleanupSnapshotRequest) (*CleanupSnapshotResponse, error)
	// CopySnapshot copies every file of src_uri to dst_uri, overwriting files
	// already at dst_uri. src_uri and dst_uri may be in different buckets. It
	// returns FAILED_PRECONDITION if src_uri holds no files.
	CopySnapshot(context.Context, *CopySnapshotRequest) (*CopySnapshotResponse, error)
	mustEmbedUnimplementedServerProviderPluginServer()
}

// UnimplementedServerProviderPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerProviderPluginServer struct{}

func (UnimplementedServerProviderPluginServer) CleanupSnapshot(context.Context, *CleanupSnapshotRequest) (*CleanupSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupSnapshot not implemented")
}
func (UnimplementedServerProviderPluginServer) CopySnapshot(context.Context, *CopySnapshotRequest) (*CopySnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopySnapshot not implemented")
}
func (UnimplementedServerProviderPluginServer) mustEmbedUnimplementedServerProviderPluginServer() {}
func (UnimplementedServerProviderPluginServer) testEmbeddedByValue()                              {}

// UnsafeServerProviderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerProviderPluginServer will
// result in compilation errors.
type UnsafeServerProviderPluginServer interface {
	mustEmbedUnimplementedServerProviderPluginServer()
}

func RegisterServerProviderPluginServer(s grpc.ServiceRegistrar, srv ServerProviderPluginServer) {
	// If the following call panics, it indicates UnimplementedServerProviderPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerProviderPlugin_ServiceDesc, srv)
}

func _ServerProviderPlugin_CleanupSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerProviderPluginServer).CleanupSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerProviderPlugin_CleanupSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerProviderPluginServer).CleanupSnapshot(ctx, req.(*CleanupSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerProviderPlugin_CopySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerProviderPluginServer).CopySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerProviderPlugin_CopySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerProviderPluginServer).CopySnapshot(ctx, req.(*CopySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerProviderPlugin_ServiceDesc is the grpc.ServiceDesc for ServerProviderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshotplugin.v1.ServerProviderPlugin",
	HandlerType: (*ServerProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CleanupSnapshot",
			Handler:    _ServerProviderPlugin_CleanupSnapshot_Handler,
		},
		{
			MethodName: "CopySnapshot",
			Handler:    _ServerProviderPlugin_CopySnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snapshotplugin.proto",
}
