// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: snapshotplugin.proto

package snapshotpluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchSnapshotRequest asks the plugin to download snapshot files.
type FetchSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The snapshot to read, e.g. gs://<bucket>/<prefix>/.
	SnapshotUri string `protobuf:"bytes,1,opt,name=snapshot_uri,json=snapshotUri,proto3" json:"snapshot_uri,omitempty"`
	// The JWT of the actor that owns the snapshot, for plugins that authorize
	// storage access per actor. Empty when the plugin uses its own credentials.
	ActorJwt string `protobuf:"bytes,2,opt,name=actor_jwt,json=actorJwt,proto3" json:"actor_jwt,omitempty"`
	// Absolute local directory the files are written into. It must exist.
	WritePath string `protobuf:"bytes,3,opt,name=write_path,json=writePath,proto3" json:"write_path,omitempty"`
	// Base names of the files to download. Required; names containing a path
	// separator or ".." are rejected with INVALID_ARGUMENT.
	Files         []string `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSnapshotRequest) Reset() {
	*x = FetchSnapshotRequest{}
	mi := &file_snapshotplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnapshotRequest) ProtoMessage() {}

func (x *FetchSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnapshotRequest.ProtoReflect.Descriptor instead.
func (*FetchSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSnapshotRequest) GetSnapshotUri() string {
	if x != nil {
		return x.SnapshotUri
	}
	return ""
}

func (x *FetchSnapshotRequest) GetActorJwt() string {
	if x != nil {
		return x.ActorJwt
	}
	return ""
}

func (x *FetchSnapshotRequest) GetWritePath() string {
	if x != nil {
		return x.WritePath
	}
	return ""
}

func (x *FetchSnapshotRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// FetchSnapshotResponse is empty; success means every file was written.
type FetchSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSnapshotResponse) Reset() {
	*x = FetchSnapshotResponse{}
	mi := &file_snapshotplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnapshotResponse) ProtoMessage() {}

func (x *FetchSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnapshotResponse.ProtoReflect.Descriptor instead.
func (*FetchSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{1}
}

// UploadSnapshotRequest asks the plugin to upload snapshot files.
type UploadSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The snapshot to write, e.g. gs://<bucket>/<prefix>/.
	SnapshotUri string `protobuf:"bytes,1,opt,name=snapshot_uri,json=snapshotUri,proto3" json:"snapshot_uri,omitempty"`
	// The JWT of the actor that owns the snapshot, for plugins that authorize
	// storage access per actor. Empty when the plugin uses its own credentials.
	ActorJwt string `protobuf:"bytes,2,opt,name=actor_jwt,json=actorJwt,proto3" json:"actor_jwt,omitempty"`
	// Absolute local directory the files are read from.
	LocalPath string `protobuf:"bytes,3,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	// Base names of the files to upload. Required; names containing a path
	// separator or ".." are rejected with INVALID_ARGUMENT.
	Files         []string `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnapshotRequest) Reset() {
	*x = UploadSnapshotRequest{}
	mi := &file_snapshotplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnapshotRequest) ProtoMessage() {}

func (x *UploadSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UploadSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{2}
}

func (x *UploadSnapshotRequest) GetSnapshotUri() string {
	if x != nil {
		return x.SnapshotUri
	}
	return ""
}

func (x *UploadSnapshotRequest) GetActorJwt() string {
	if x != nil {
		return x.ActorJwt
	}
	return ""
}

func (x *UploadSnapshotRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadSnapshotRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// UploadSnapshotResponse is empty; success means every file is durably stored.
type UploadSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnapshotResponse) Reset() {
	*x = UploadSnapshotResponse{}
	mi := &file_snapshotplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnapshotResponse) ProtoMessage() {}

func (x *UploadSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UploadSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{3}
}

// CleanupSnapshotRequest names the snapshots to delete.
type CleanupSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A snapshot URI, or the prefix of a resource that owns several snapshots
	// (e.g. gs://<bucket>/<root>/atespaces/<atespace>/actors/<uid>). Every file
	// below it is deleted. A bare bucket is rejected with INVALID_ARGUMENT.
	SnapshotUri   string `protobuf:"bytes,1,opt,name=snapshot_uri,json=snapshotUri,proto3" json:"snapshot_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupSnapshotRequest) Reset() {
	*x = CleanupSnapshotRequest{}
	mi := &file_snapshotplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupSnapshotRequest) ProtoMessage() {}

func (x *CleanupSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CleanupSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{4}
}

func (x *CleanupSnapshotRequest) GetSnapshotUri() string {
	if x != nil {
		return x.SnapshotUri
	}
	return ""
}

// CleanupSnapshotResponse is empty.
type CleanupSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupSnapshotResponse) Reset() {
	*x = CleanupSnapshotResponse{}
	mi := &file_snapshotplugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupSnapshotResponse) ProtoMessage() {}

func (x *CleanupSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CleanupSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{5}
}

// CopySnapshotRequest names the source and destination snapshots.
type CopySnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcUri        string                 `protobuf:"bytes,1,opt,name=src_uri,json=srcUri,proto3" json:"src_uri,omitempty"`
	DstUri        string                 `protobuf:"bytes,2,opt,name=dst_uri,json=dstUri,proto3" json:"dst_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopySnapshotRequest) Reset() {
	*x = CopySnapshotRequest{}
	mi := &file_snapshotplugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopySnapshotRequest) ProtoMessage() {}

func (x *CopySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopySnapshotRequest.ProtoReflect.Descriptor instead.
func (*CopySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{6}
}

func (x *CopySnapshotRequest) GetSrcUri() string {
	if x != nil {
		return x.SrcUri
	}
	return ""
}

func (x *CopySnapshotRequest) GetDstUri() string {
	if x != nil {
		return x.DstUri
	}
	return ""
}

// CopySnapshotResponse is empty.
type CopySnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopySnapshotResponse) Reset() {
	*x = CopySnapshotResponse{}
	mi := &file_snapshotplugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopySnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopySnapshotResponse) ProtoMessage() {}

func (x *CopySnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshotplugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopySnapshotResponse.ProtoReflect.Descriptor instead.
func (*CopySnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshotplugin_proto_rawDescGZIP(), []int{7}
}

var File_snapshotplugin_proto protoreflect.FileDescriptor

const file_snapshotplugin_proto_rawDesc = "" +
	"\n" +
	"\x14snapshotplugin.proto\x12\x0esnapshotplugin\"\x8b\x01\n" +
	"\x14FetchSnapshotRequest\x12!\n" +
	"\fsnapshot_uri\x18\x01 \x01(\tR\vsnapshotUri\x12\x1b\n" +
	"\tactor_jwt\x18\x02 \x01(\tR\bactorJwt\x12\x1d\n" +
	"\n" +
	"write_path\x18\x03 \x01(\tR\twritePath\x12\x14\n" +
	"\x05files\x18\x04 \x03(\tR\x05files\"\x17\n" +
	"\x15FetchSnapshotResponse\"\x8c\x01\n" +
	"\x15UploadSnapshotRequest\x12!\n" +
	"\fsnapshot_uri\x18\x01 \x01(\tR\vsnapshotUri\x12\x1b\n" +
	"\tactor_jwt\x18\x02 \x01(\tR\bactorJwt\x12\x1d\n" +
	"\n" +
	"local_path\x18\x03 \x01(\tR\tlocalPath\x12\x14\n" +
	"\x05files\x18\x04 \x03(\tR\x05files\"\x18\n" +
	"\x16UploadSnapshotResponse\";\n" +
	"\x16CleanupSnapshotRequest\x12!\n" +
	"\fsnapshot_uri\x18\x01 \x01(\tR\vsnapshotUri\"\x19\n" +
	"\x17CleanupSnapshotResponse\"G\n" +
	"\x13CopySnapshotRequest\x12\x17\n" +
	"\asrc_uri\x18\x01 \x01(\tR\x06srcUri\x12\x17\n" +
	"\adst_uri\x18\x02 \x01(\tR\x06dstUri\"\x16\n" +
	"\x14CopySnapshotResponse2\xd7\x01\n" +
	"\x12NodeProviderPlugin\x12^\n" +
	"\rFetchSnapshot\x12$.snapshotplugin.FetchSnapshotRequest\x1a%.snapshotplugin.FetchSnapshotResponse\"\x00\x12a\n" +
	"\x0eUploadSnapshot\x12%.snapshotplugin.UploadSnapshotRequest\x1a&.snapshotplugin.UploadSnapshotResponse\"\x002\xd9\x01\n" +
	"\x14ServerProviderPlugin\x12d\n" +
	"\x0fCleanupSnapshot\x12&.snapshotplugin.CleanupSnapshotRequest\x1a'.snapshotplugin.CleanupSnapshotResponse\"\x00\x12[\n" +
	"\fCopySnapshot\x12#.snapshotplugin.CopySnapshotRequest\x1a$.snapshotplugin.CopySnapshotResponse\"\x00BAZ?github.com/agent-substrate/substrate/pkg/proto/snapshotpluginpbb\x06proto3"

var (
	file_snapshotplugin_proto_rawDescOnce sync.Once
	file_snapshotplugin_proto_rawDescData []byte
)

func file_snapshotplugin_proto_rawDescGZIP() []byte {
	file_snapshotplugin_proto_rawDescOnce.Do(func() {
		file_snapshotplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshotplugin_proto_rawDesc), len(file_snapshotplugin_proto_rawDesc)))
	})
	return file_snapshotplugin_proto_rawDescData
}

var file_snapshotplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_snapshotplugin_proto_goTypes = []any{
	(*FetchSnapshotRequest)(nil),    // 0: snapshotplugin.FetchSnapshotRequest
	(*FetchSnapshotResponse)(nil),   // 1: snapshotplugin.FetchSnapshotResponse
	(*UploadSnapshotRequest)(nil),   // 2: snapshotplugin.UploadSnapshotRequest
	(*UploadSnapshotResponse)(nil),  // 3: snapshotplugin.UploadSnapshotResponse
	(*CleanupSnapshotRequest)(nil),  // 4: snapshotplugin.CleanupSnapshotRequest
	(*CleanupSnapshotResponse)(nil), // 5: snapshotplugin.CleanupSnapshotResponse
	(*CopySnapshotRequest)(nil),     // 6: snapshotplugin.CopySnapshotRequest
	(*CopySnapshotResponse)(nil),    // 7: snapshotplugin.CopySnapshotResponse
}
var file_snapshotplugin_proto_depIdxs = []int32{
	0, // 0: snapshotplugin.NodeProviderPlugin.FetchSnapshot:input_type -> snapshotplugin.FetchSnapshotRequest
	2, // 1: snapshotplugin.NodeProviderPlugin.UploadSnapshot:input_type -> snapshotplugin.UploadSnapshotRequest
	4, // 2: snapshotplugin.ServerProviderPlugin.CleanupSnapshot:input_type -> snapshotplugin.CleanupSnapshotRequest
	6, // 3: snapshotplugin.ServerProviderPlugin.CopySnapshot:input_type -> snapshotplugin.CopySnapshotRequest
	1, // 4: snapshotplugin.NodeProviderPlugin.FetchSnapshot:output_type -> snapshotplugin.FetchSnapshotResponse
	3, // 5: snapshotplugin.NodeProviderPlugin.UploadSnapshot:output_type -> snapshotplugin.UploadSnapshotResponse
	5, // 6: snapshotplugin.ServerProviderPlugin.CleanupSnapshot:output_type -> snapshotplugin.CleanupSnapshotResponse
	7, // 7: snapshotplugin.ServerProviderPlugin.CopySnapshot:output_type -> snapshotplugin.CopySnapshotResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snapshotplugin_proto_init() }
func file_snapshotplugin_proto_init() {
	if File_snapshotplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshotplugin_proto_rawDesc), len(file_snapshotplugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_snapshotplugin_proto_goTypes,
		DependencyIndexes: file_snapshotplugin_proto_depIdxs,
		MessageInfos:      file_snapshotplugin_proto_msgTypes,
	}.Build()
	File_snapshotplugin_proto = out.File
	file_snapshotplugin_proto_goTypes = nil
	file_snapshotplugin_proto_depIdxs = nil
}
